function [approximateIntegral, subintervalWidth, metadata] = simpson_rule( ...
    functionHandle, lowerBound, upperBound, subintervalCount)
    narginchk(4, 4);

    if ~isa(functionHandle, 'function_handle')
        error('simpson_rule:InvalidFunctionHandle', ...
            'functionHandle must be a valid function handle.');
    end

    validateattributes(lowerBound, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, 'lowerBound', 2);
    validateattributes(upperBound, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, 'upperBound', 3);
    validateattributes(subintervalCount, {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', 'positive'}, ...
        mfilename, 'subintervalCount', 4);

    if upperBound <= lowerBound
        error('simpson_rule:InvalidInterval', ...
            'upperBound must be greater than lowerBound.');
    end

    if mod(subintervalCount, 2) ~= 0
        error('simpson_rule:InvalidSubintervalCount', ...
            'subintervalCount must be even for Simpson''s rule.');
    end

    subintervalWidth = (upperBound - lowerBound) / subintervalCount;
    xNodes = linspace(lowerBound, upperBound, subintervalCount + 1);
    yNodes = functionHandle(xNodes);

    validateattributes(yNodes, {'numeric'}, ...
        {'real', 'finite', 'vector', 'numel', subintervalCount + 1}, ...
        mfilename, 'functionHandle(xNodes)');

    yNodes = yNodes(:).';
    oddIndexedTerms = sum(yNodes(2:2:end-1));
    evenIndexedTerms = sum(yNodes(3:2:end-2));

    approximateIntegral = (subintervalWidth / 3) * ...
        (yNodes(1) + yNodes(end) + 4 * oddIndexedTerms + 2 * evenIndexedTerms);

    metadata = struct( ...
        'lowerBound', lowerBound, ...
        'upperBound', upperBound, ...
        'subintervalCount', subintervalCount, ...
        'subintervalWidth', subintervalWidth, ...
        'xNodes', xNodes, ...
        'yNodes', yNodes);
end
