function [approximateIntegral, subintervalWidth, metadata] = trapezoidal_rule( ...
    functionHandle, lowerBound, upperBound, subintervalCount)
    narginchk(4, 4);

    if ~isa(functionHandle, 'function_handle')
        error('trapezoidal_rule:InvalidFunctionHandle', ...
            'functionHandle must be a valid function handle.');
    end

    validateattributes(lowerBound, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, 'lowerBound', 2);
    validateattributes(upperBound, {'numeric'}, ...
        {'real', 'finite', 'scalar'}, mfilename, 'upperBound', 3);
    validateattributes(subintervalCount, {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', 'positive'}, ...
        mfilename, 'subintervalCount', 4);

    if upperBound <= lowerBound
        error('trapezoidal_rule:InvalidInterval', ...
            'upperBound must be greater than lowerBound.');
    end

    subintervalWidth = (upperBound - lowerBound) / subintervalCount;
    xNodes = linspace(lowerBound, upperBound, subintervalCount + 1);
    yNodes = functionHandle(xNodes);

    validateattributes(yNodes, {'numeric'}, ...
        {'real', 'finite', 'vector', 'numel', subintervalCount + 1}, ...
        mfilename, 'functionHandle(xNodes)');

    yNodes = yNodes(:).';
    approximateIntegral = subintervalWidth * ...
        ((yNodes(1) + yNodes(end)) / 2 + sum(yNodes(2:end-1)));

    metadata = struct( ...
        'lowerBound', lowerBound, ...
        'upperBound', upperBound, ...
        'subintervalCount', subintervalCount, ...
        'subintervalWidth', subintervalWidth, ...
        'xNodes', xNodes, ...
        'yNodes', yNodes);
end
