function result = problem_interpolation()
    xData = [8; 10; 12; 14; 16];
    yData = [120; 185; 260; 230; 170];
    evaluationPoints = [11; 13];

    [lagrangeValues, lagrangeCoefficients] = ...
        lagrange_interpolation(xData, yData, evaluationPoints);

    [newtonValues, dividedDifferenceTable] = ...
        newton_interpolation(xData, yData, evaluationPoints);

    densePoints = linspace(min(xData), max(xData), 400);
    lagrangeCurve = lagrange_interpolation(xData, yData, densePoints);
    newtonCurve = newton_interpolation(xData, yData, densePoints);

    problemFigure = figure('Name', 'Polynomial Interpolation', 'NumberTitle', 'off');
    plot(xData, yData, 'ok', 'MarkerSize', 8, 'MarkerFaceColor', 'k', ...
        'DisplayName', 'Known data');
    hold on;
    plot(densePoints, lagrangeCurve, '--r', 'LineWidth', 1.5, ...
        'DisplayName', 'Lagrange interpolation');
    plot(densePoints, newtonCurve, ':b', 'LineWidth', 2, ...
        'DisplayName', 'Newton interpolation');
    plot(evaluationPoints, lagrangeValues, 'dr', 'MarkerSize', 8, ...
        'MarkerFaceColor', 'r', 'DisplayName', 'Estimated points');
    grid on;
    xlabel('Time (hours)');
    ylabel('Traffic (Mbps)');
    title('Lagrange vs Newton Interpolation');
    legend('Location', 'best');
    hold off;

    resultTable = table( ...
        evaluationPoints, ...
        lagrangeValues, ...
        newtonValues, ...
        abs(lagrangeValues - newtonValues), ...
        'VariableNames', {'EvaluationPoint', 'LagrangeValue', 'NewtonValue', 'Difference'});

    disp('=== PROBLEM 3: INTERPOLATION ===');
    disp(resultTable);
    disp('Lagrange coefficients (ascending powers):');
    disp(lagrangeCoefficients);
    disp('Newton divided difference table:');
    disp(dividedDifferenceTable);

    coefficientTable = table( ...
        (0:(numel(lagrangeCoefficients) - 1)).', ...
        lagrangeCoefficients(:), ...
        'VariableNames', {'Power', 'Coefficient'});

    dividedDifferenceVariableNames = strcat("Column", string(1:size(dividedDifferenceTable, 2)));
    dividedDifferenceExportTable = array2table(dividedDifferenceTable, ...
        'VariableNames', cellstr(dividedDifferenceVariableNames));

    save_figure_file(problemFigure, 'problem_3_interpolation');
    save_table_file(resultTable, 'problem_3_interpolation_estimates');
    save_table_file(coefficientTable, 'problem_3_lagrange_coefficients');
    save_table_file(dividedDifferenceExportTable, 'problem_3_newton_divided_differences');

    result = struct( ...
        'problemNumber', 3, ...
        'title', 'Polynomial Interpolation', ...
        'summary', sprintf(['Lagrange and Newton interpolation produce identical ', ...
            'estimates at x = 11 and x = 13, confirming that both formulations ', ...
            'represent the same interpolating polynomial.']), ...
        'mainTable', resultTable);
end
